

export enum ESTADOS {
    PENDIENTE = "PENDIENTE",
    PREPARADO = "PREPARADO",
    DESPACHADO = "DESPACHADO",
    ENTREGADO = "ENTREGADO",
    NO_ENTREGADO = "NO ENTREGADO",
    ENTRADA = "ENTRADA",
    EXTRAVIADO = "EXTRAVIADO",
    DEVOLUCION = "DEVOLUCION"
}